### ISSUE TITLE
Auto-progress isn't working with vaadin/angular2-polymer

### ISSUE THREAD

**Issue by florent1933** [Link2Twenty/l2t-paper-slider#10]
``` HTML
<l2t-paper-slider auto-progress disable-swipe slide-duration="1" position="2" total-slides="4">
  <paper-slide style="background-image: url('https://images.unsplash.com/photo-1418662589339-364ad47f98a2?dpr=2&auto=format&crop=entropy&fit=crop&w=1500&h=1007&q=80');"></paper-slide>
  <paper-slide style="background-image: url('https://images.unsplash.com/photo-1421151051865-b98b5f93dc13?dpr=2&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80');"></paper-slide>
  <paper-slide style="background-image: url('https://images.unsplash.com/photo-1420393000485-4697383da9ec?dpr=2&auto=format&crop=entropy&fit=crop&w=1500&h=1125&q=80');"></paper-slide>
  <paper-slide style="background-image: url('https://images.unsplash.com/photo-1433800881591-a31e7bff3f22?dpr=2&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80');"></paper-slide>
</l2t-paper-slider>
```

**Comment by Link2Twenty** [comment]
Which browser are you using? Does anything come up in the console log?

I've tested your code in IE, Edge, Firefox and Chrome and it seems to work.

https://jsfiddle.net/link2twenty/1cLofqny/

**Comment by florent1933** [comment]
Sorry for the missing informations.

It's not working in any browser. I use your webcomponent with Angular2 and Polymer. The bridge between this 2 frameworks is [vaadin/angular2-polymer](https://github.com/vaadin/angular2-polymer).

Everything is working except auto-progress. I have nothing in the console.

**Comment by Link2Twenty** [comment]
No worries, in your console can you type 

``` JS
document.querySelector("l2t-paper-slider").autoProgress
```

That will return `true` or `false`, depending on whether or not it's set to `auto-progress`.

if it returns `false`try typing 

``` JS
document.querySelector("l2t-paper-slider").autoProgress = true
```

That should start it moving.

On a side note, it's worth mentioning that the progress is paused when you have your mouse over the element.

**Comment by florent1933** [comment]
`
document.querySelector("l2t-paper-slider").autoProgress
`
return true

Thanks for the sidenote, I tried to put my mouse out of the slider but not working. If you want to find the problem: the link of the repo is: https://github.com/florent1933/reservation

**Comment by Link2Twenty** [comment]
There was a bug saving intervals as global variables (which was causing some issues elsewhere). It's now been patched so worth seeing if it's solved this too.
