### ISSUE TITLE
Change custom property

### ISSUE THREAD

**Issue by MarcosGalaviz** [Link2Twenty/l2t-paper-slider#12]
Hi this component is great, but Im just starting with polymer and I would like to change some custom properties like : **--paper-slide-height** with media query but I cant :( I have also tried with iron-media-query but doesnt work ¿is there a way to do that?

For example what I need is that the custom property --paper-slide-height is one in small screens and other in biger screens.

Thanks a lot for your help.

**Comment by Link2Twenty** [comment]
This, unfortunately, is a limitation of the way CSS variables work.

For size what I would suggest doing is set the height and width of the element to 100% and put the whole element in a container div (which you can size with CSS) then the element will stay the same size as it's parent.

**Comment by Link2Twenty** [comment]
Here is an example of it in action

https://jsfiddle.net/link2twenty/foz7f0o4/

resize the preview pane to see it change.
