### ISSUE TITLE
I'm not able to make work auto-progress, when i put two l2t-paper-slider components in the same page

### ISSUE THREAD

**Issue by alberto-donat** [Link2Twenty/l2t-paper-slider#13]
I'm not able to make work auto-progress, when i put two l2t-paper-slider components in the same page

It seems that there could be a conflict between components. One of them, does not move, and the other one, moves too fast.

Can anybody help me with this issue

Thanks in advance

**Comment by Link2Twenty** [comment]
Man oh man, what missing 3 little characters can do.

I'd missed `var`off the beginning of [l2t-paper-slider.html#L323](https://github.com/Link2Twenty/l2t-paper-slider/blob/master/l2t-paper-slider.html#L323) meaning I was setting `this$` as a global variable.

Fixed now.

**Comment by alberto-donat** [comment]
Good job, well done

Thanks a lot
