### ISSUE TITLE
Can't use dom-repeat inside <l2t-paper-slider>

### ISSUE THREAD

**Issue by kaungmyatlwin** [Link2Twenty/l2t-paper-slider#18]
Hello. I was trying to make slides more dynamic (with help of `dom-repeat`) and it seems like it's not working.

Here's the error.

`Uncaught TypeError: Cannot read property 'removeAttribute' of undefined (on line: 446)`

Here is my code to implement `dom-repeat`

```
      <l2t-paper-slider total-slides="11" sensitivity="high">
        <template is="dom-repeat" items="[[things]]" as="thing">
          <paper-slide class="text-center">
            <p>[[thing.text]]
          </paper-slide>
        </template>
      </l2t-paper-slider>
```

As far as I know, `sideSel.length` is undefined when `dom-repeat` is set in `_setInert` function.

EDIT: A quick fix for this problem is to remove `this._setInert()` function call at line: 423. This method worked for me.

**Comment by Link2Twenty** [comment]
OK, I've patched it to master (but not to a release)

can you try it out here and let me know if that solves everything

https://jsfiddle.net/link2twenty/5kp15L5L/

Thanks 🙂

**Comment by Link2Twenty** [comment]
I've pushed it to a new release.

**Comment by kaungmyatlwin** [comment]
Thanks. Your solution worked here! :+1:
