### ISSUE TITLE
Update to 2.0

### ISSUE THREAD

**Issue by santanafabio** [Link2Twenty/l2t-paper-slider#21]
Hey buddy, are you thinking to update to Polymer 2.0

**Comment by Link2Twenty** [comment]
It will currently work with polymer 1 and 2, though moving over to 2 only is on my to-do list ☺️

**Comment by santanafabio** [comment]
Can I try to do it and send to you?

**Comment by Link2Twenty** [comment]
Try?
Trying using it with Polymer2? Or try making it polymer2 only?

**Comment by santanafabio** [comment]
Making Polymer-2.0 only

**Comment by Link2Twenty** [comment]
Sure, submit a pull request. Might take a while for me to accept it though, I'd like to keep backwards compatible for a while.
