### ISSUE TITLE
Slider does not display text

### ISSUE THREAD

**Issue by NeoLegends** [Link2Twenty/l2t-paper-slider#22]
For the love of god I cannot make the slides display text content. Image content works fine, but as soon as I use text inside the `<paper-slide>`, it does not show up. It is as if the `font-size` were zero. All the `p`s and `h2`s, etc. have a height of 0. Any idea why? The examples do not work for me.

I'm using polymer 2.0-rc.2 in Chrome.

**Comment by NeoLegends** [comment]
Found the issue! Seems like `font-size: 0` ([Line 63](https://github.com/Link2Twenty/l2t-paper-slider/blob/master/l2t-paper-slider.html#L63)) from `.slider__slides` bleeds through the shadow dom and causes the text to disappear.

This would've been easy to spot, however, that property never shows up inside the Chrome debugger. Probably because it should've been masked away by shadow DOM. I only found the reason for this because I used the Firefox debugger (Firefox does not have native support of shadow dom yet), and the style bled through shady dom there and was visible.

Is this desired behavior?

**Comment by Link2Twenty** [comment]
At ([Line 126](https://github.com/Link2Twenty/l2t-paper-slider/blob/master/l2t-paper-slider.html#L126)) it's supposed to set the size back to medium again (which works in polymer1).
I set it to 0 to remove the space between slides.

I'll look into why it doesn't pick it up in for Polymer 2

**Comment by Link2Twenty** [comment]
Looking at it `:host ::slotted, :host ::content * ` should probably be `:host ::slotted *, :host ::content * ` can you change it in your local copy and see if it fixes it (line 125)

**Comment by santanafabio** [comment]
Actually is:

```
      ::slotted(*), :host ::content * {
        font-size: medium;
      }
      ::slotted(paper-slide), :host ::content paper-slide{
        width: var(--paper-slide-width, 100%);
        height: var(--paper-slide-height, 600px);
        overflow-x: hidden;
        display: inline-block;
      }
```

Almost finishing the version for polymer 2.0... the is, i dont f... know how to commit for u @Link2Twenty . New at this git comunity thing.

I'll search later and commit for u

**Comment by Link2Twenty** [comment]
Resolved
