### ISSUE TITLE
paper-slide not rendered

### ISSUE THREAD

**Issue by arlejeun** [Link2Twenty/l2t-paper-slider#24]
I'm using shady-dom and when I tried to run your custom-element into my project, the paper-slide element was not rendered. Any idea? I couldn't find it into your repository

**Comment by Link2Twenty** [comment]
Is this will polymer 1 or 2?
Can you show me an example on jsfiddle (or somewhere like that)?

**Comment by Link2Twenty** [comment]
Can you try it again (with the latest version) and let me know if it's working now.

**Comment by arlejeun** [comment]
It works like a charm now with Polymer 1. Thanks for your help!
