### ISSUE TITLE
dom-repeat + dynamic data: binding 'total-slides' to array length throws

### ISSUE THREAD

**Issue by pdesjardins90** [Link2Twenty/l2t-paper-slider#25]
I use it like this: 
````html
    <l2t-paper-slider total-slides="[[pictures.length]]" hide-nav="true" sensitivity="high">
        <template is="dom-repeat" items="[[pictures]]">
            <paper-slide>
                <iron-image src="[[item.url]]" sizing="cover"></iron-image>
            </paper-slide>
        </template>
    </l2t-paper-slider>
````

It works, but there's an error thrown 4 times in the console:
````text
keyframe-effect-constructor.js:168 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at value (keyframe-effect-constructor.js:168)
    at HTMLElement._moveManual (l2t-paper-slider.html:431)
    at l2t-paper-slider.html:580
````

However when I set 'total-slides' to a fixed number, no error is thrown

EDIT: it's thrown 4 times because I receive 4 pictures from my API

**Comment by pdesjardins90** [comment]
I also tried binding to a computed property that returns 0 if pictures is equivalent to null, didn't solve it

**Comment by Link2Twenty** [comment]
Can you try modifying this so it throws the error too

https://jsfiddle.net/link2twenty/3jL0j0tf/

Thanks

**Comment by pdesjardins90** [comment]
Here you go: https://jsfiddle.net/3jL0j0tf/17/
(Forgot to say, I use chrome 57)

**Comment by Link2Twenty** [comment]
Hmm, you can't really assign an array like that (at least it didn't work for me)

but doing it like this should work

https://jsfiddle.net/link2twenty/3jL0j0tf/18/

**Comment by pdesjardins90** [comment]
Well, I tried to emulate a one-way binding in a polymer app. Say this array comes from the parent element.

**Comment by Link2Twenty** [comment]
OK, I've had another look. The only way I can get the error to happen is if I set totalSlides to 0.
I've put in a catch for that now so it won't throw errors.

The edit I've made is only on master (not pushed out with a release)
can you give the new code a try and see if the errors have gone?

Thanks

**Comment by Link2Twenty** [comment]
The patch has been pushed live, with a couple of other things.
Hopefully this solves your issues.

**Comment by pdesjardins90** [comment]
Yep, that fixed it! You rock man. Sorry for the delay, got swamped over here for the past few days
