### ISSUE TITLE
Issue with ie11

### ISSUE THREAD

**Issue by arana50** [Link2Twenty/l2t-paper-slider#27]
l2t-paper-slider doesn't work in ie11.

**Comment by Link2Twenty** [comment]
Hmm, it works for me.

Is it just a particular part that doesn't work? Or the entire thing?

If you right-click in the page and press 'inspect element' you will get a little panel at the bottom of your screen, are there any errors in the console section?

![ie11](https://cloud.githubusercontent.com/assets/3534427/26066779/f30b66ca-398f-11e7-88e3-4f00ffe0b091.gif)
