### ISSUE TITLE
l2t doesn't work with Safari

### ISSUE THREAD

**Issue by MattStopa** [Link2Twenty/l2t-paper-slider#30]
Unless I'm crazy I think the following code needs to be changed. Below you are comparing a float against a string. So in my case my polymer version is "1.9.1" so yes it's greater than 2 as far as strings go. 

` 
//allow vertical scrolling
if (Polymer.version >= "2") {
  Polymer.Gestures.addListener(this.$.container, 'track', e => this._swipeHandler(e));
}
`

I think you just want 

`if (Polymer.version >= 2)`

I love this slider but it's breaking for me :-(

**Comment by Link2Twenty** [comment]
I thought the comparisons were a bit more intelligent than that (I could be wrong of course).

Do these work out ok for you?
https://jsfiddle.net/0g96a6gs/1/
It should be true, false, true
