### ISSUE TITLE
Can't use it with polymer

### ISSUE THREAD

**Issue by MarcosGalaviz** [Link2Twenty/l2t-paper-slider#31]
Hi, I am trying to use this component with polymer but when I run Polymer Build I have this error, I dont know why :(

error:   Uncaught exception: Error in plugin 'gulp-htmlmin'
Parse Error: <input id="toggle3" type="checkbox" <="" label="">
          <label>Toggling the outer inert after toggling the inner inert should not modify its state either. <input id="toggle4" type="checkbox" checked=""></label> </label></h2>

      <div id="outercontent" class="container" inert="">
        <p>
          Clicking the checkbox above will toggle the element's <code>inert</code> property via </p><pre><code>element.inert = evt.target.checked == true;</code></pre>
          <a href="javascript:alert('clicked')">You should<span class="not">n't</span> be able to click this or set focus to it.</a>.

          <section id="innercontent2">
            <h3>This inner section is <span class="inner-not">not</span> marked inert</h3>
            <p><a href="javascript:alert('clicked')">Toggling the inner inert should not make this link become clickable or tabbable.</a></p>
            <span role="link" tabindex="0">Toggling the inner inert should not make this fake link become tabbable or clickable either.</span>
          </section>

        <p></p>
      </div>
    </section>

    <script src="dist/inert.js"></script>
    <script src="index.html_script_0.js"></script>

</body></html>
error:   Error: Parse Error: <input id="toggle3" type="checkbox" <="" label="">
          <label>Toggling the outer inert after toggling the inner inert should not modify its state either. <input id="toggle4" type="checkbox" checked=""></label> </label></h2>
![image](https://user-images.githubusercontent.com/14163318/28370230-5be7f814-6c5f-11e7-990d-97d35c044254.png)

``

![error](https://user-images.githubusercontent.com/14163318/28370302-86ddcabc-6c5f-11e7-8cec-8d71a90ef88d.jpg)

**Comment by Link2Twenty** [comment]
Hi, can you modify this code to be the same as yours (there is a fork option)

https://jsfiddle.net/link2twenty/foz7f0o4/

**Comment by Link2Twenty** [comment]
Feel free to open it again if I'm wrong, but I don't think this is related to my element
