### ISSUE TITLE
total-slides attribute?

### ISSUE THREAD

**Issue by mvpmvh** [Link2Twenty/l2t-paper-slider#32]
What is the significance in declaring the `total-slides`? Is there a reason this must be provided, as opposed to simply calculating the number of distributed `<paper-slide>`?

**Comment by Link2Twenty** [comment]
I think there were some timing issues, it uses the number to render in a bunch of stuff (the dots for example).

**Comment by mvpmvh** [comment]
do u mind going into detail about the timing issues u faced? I'm hoping it's something that can be resolved using an observer on slotted nodes (https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#observe-nodes)

**Comment by Link2Twenty** [comment]
Finally got round to testing this and you were right, Now you can leave it blank and it will work it out for you.
