### ISSUE TITLE
_countSlides broken in 2.0.1 and 2.0.2

### ISSUE THREAD

**Issue by jab** [Link2Twenty/l2t-paper-slider#38]
I just tried upgrading from 2.0.0 and it broke the l2t-paper-slider on my site. I spent some time debugging and it looks like `_countSlides` is now always returning 0 rather than the correct number of `paper-slide` elements I have. I tested 2.0.1 and 2.0.2 and found it broken in both. I am using latest Polymer v2.3.1. I am downgrading to 2.0.0 until this is fixed.

Hope this helps and thanks for releasing this handy element!

**Comment by Link2Twenty** [comment]
Gah, I thought 2.0.2 fixed that. I'm sorry it broke for you 😕

Can you change this example to break it?
https://jsfiddle.net/link2twenty/8rnbtLb1/

Thanks 🙂

**Comment by Link2Twenty** [comment]
Hmm, I think it works with shady Dom but not shadow.

**Comment by Link2Twenty** [comment]
v2.0.3 should fix this 🙂

Thanks for submitting a bug report.

**Comment by jab** [comment]
Confirmed! Thanks for the quick fix! 😻
