### ISSUE TITLE
README lists public attributes in camelCase when they are in fact hyphen-separated

### ISSUE THREAD

**Issue by galacemiguel** [Link2Twenty/l2t-paper-slider#39]
This tripped me up, so this might help some:
- `autoProgress` should be `auto-progress`
- `slideDuration` should be `slide-duration`
- `hideNav` should be `hide-nav`
- `disableSwipe` should be `disable-swipe`

**Comment by Link2Twenty** [comment]
In polymer, properties can be accessed via HTML or by JS. Javascript uses camelCase but as HTML doesn't care about the case it maps them to have a hyphen.
```JS
document.querySelector('l2t-paper-slider').slideDuration = 2;
```
is the same as
```HTML
<l2t-paper-slider slide-duration="2"></l2t-paper-slider>
```

Here is their documentation that mentions it.

https://www.polymer-project.org/2.0/docs/devguide/properties#property-name-mapping

**Comment by galacemiguel** [comment]
Had no idea. Thanks for this!
