### ISSUE TITLE
Not working if Document-level global Polymer settings is set.

### ISSUE THREAD

**Issue by sagarrshd** [Link2Twenty/l2t-paper-slider#5]
The slider is not working if we create a Document-level global Polymer object as shown [here](https://www.polymer-project.org/1.0/docs/devguide/settings).

The issue occurs only if dom is set as shadow.

**Comment by Link2Twenty** [comment]
Problem seems to be with `insertRule` and shadow dom.

I'll investigate.

**Comment by Link2Twenty** [comment]
Right so the problem is actually with `this._scopeSelector`, which makes it so you can register more than one element.

I may have to find another solution for my styling issues.

**Comment by Link2Twenty** [comment]
I think we're sorted (it seemed to work for me anyway). Get the latest version and give it a go.

Thanks for the bug report :+1:
