### ISSUE TITLE
issue modifying component content

### ISSUE THREAD

**Issue by eszechet80** [Link2Twenty/l2t-paper-slider#6]
Hi! gret component!

i don't know if i'm doing something wrong here...

i have a list of links, each open a detail with a l2p-paper-slider.
Each one can have different amount of images (paper-slide) (what changes is the # of paper-slides inside and the total-slides property (both data-binded)).

If i go from an item with 4 items to another one with 3, it works great. but if i got to another with 4 again, the 4th dot cannot get clicked. I think when it adds another "dot" the listener is not getting added?  (this also messes some of the styles in the dot indicator)

Thanks!

**Comment by Link2Twenty** [comment]
So this is one element that is being changed? The number of slides is being updated?

EDIT: I think I may have solved the problem. Download the latest version and give it a go.

**Comment by eszechet80** [comment]
Great!!!!! It's working now.

Thanks a lot!
