### ISSUE TITLE
swipe configuration

### ISSUE THREAD

**Issue by eszechet80** [Link2Twenty/l2t-paper-slider#7]
Hi! I love the new swipe feature! It's great! 

I have two questions regarding this.

1- Is there a way to configure how long to swipe before it triggers a slide change? as of now i have to make a very large swipe. I want it to slide when i make a short swipe
2- i have this slider on top of the page with a lot of text below. The swipe breaks the vertical scroll and i cannot scroll vertically if i start with the swipe inside the slider (which in a phone is a very large portion of the screen). Is there a way i enable the swipe on the slider without disabling the scroll?

Thanks a lot!

**Comment by Link2Twenty** [comment]
Give that a go, I've added both bits.

Generally, it's good to open multiple issues rather than have multiple questions in one :-) just makes it easier for people to keep track of everything.

Thanks for your bug report and feature request though. I appreciate it :+1:

**Comment by eszechet80** [comment]
Great!
Just updated to 1.1.4 and both things works great!

You're Awesome! Thanks!
