### ISSUE TITLE
When elements are placed on a slide, the next slides are moved

### ISSUE THREAD

**Issue by locomuco** [Link2Twenty/l2t-paper-slider#8]
see https://jsbin.com/hareba/edit?html,output

**Comment by Link2Twenty** [comment]
As a quick fix, you can do ;

``` CSS
paper-slide > * {
  display: table;
 }
```

it's caused by the div taking up 100% of the width (which spans across all the slides), changing the display to 'table' will tell it to take as much space as it needs and no more.

I will look for a better solution and patch it in soon.

**Comment by locomuco** [comment]
ok, i see, I'd like to put all kinds of elements in there ;-)

**Comment by Link2Twenty** [comment]
Quite a simple fix from my end.

I added overflow-x: hidden; so even if the added element tries to use up more than one slide it can't.
